# Generated by Django 4.0.4 on 2022-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
