# Generated by Django 4.0.4 on 2022-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_doubts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F'), ('OTHER', 'O')], max_length=10),
        ),
    ]
