# Generated by Django 4.0.4 on 2022-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_trainer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts',
            name='status',
            field=models.CharField(choices=[('SOLVED', 'solved'), ('UNSOLVED', 'unsolved')], default='Unsolved', max_length=20),
        ),
    ]
