# Generated by Django 4.0.4 on 2022-06-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
