# Generated by Django 4.0.4 on 2022-06-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doubt',
            new_name='Doubts',
        ),
    ]
